### ISSUE TITLE
docker-commandbox for Windows Containers

### ISSUE THREAD

**Issue by jim-pickering** [Ortus-Solutions/docker-commandbox#17]
Windows Containers require Docker Images to have a BaseOS whereas Linux containers do not. This ticket is requesting docker-commandbox with BaseOS for both windowservercore (windows containers) and nanoserver(hyper-v containers).

This link explains how to create the Docker Image using a Dockerfile. It requires a Docker Cloud ID, which should come from OrtusSolutions in order to be official - which is why only Ortus Solutions can do this, unless I am mistaken.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-images

Use either or both of the below images as the BaseOS, and add in the rest of the CommandBox goodness used in the Linux-based images.
https://hub.docker.com/r/microsoft/windowsservercore/
https://hub.docker.com/r/microsoft/nanoserver/

Include me as a tester, if needed.

**Comment by jclausen** [comment]
@jim-pickering : I know this has been out here for awhile. I'm looking at rolling a base image for Windows.  This will require an entirely separate set of scripts to build the image.  What I'm wondering is whether or not it makes sense to build an image with `windowserver` core, since Docker on all new versions of windows uses Hyper-V and should be able to use the `nanoserver` build.

Let me know your thoughts on whether we need to build both and I'll build a POC image.

**Comment by psarin** [comment]
Would be interested in this as well since we are trying to deploy to Windows Server 2016 and are unable to do so. Any updates? Thanks.

**Comment by jclausen** [comment]
I'm closing this one out.  While we've played around with creating separate Windows containers, even Azure support doesn't recommend using Windows containers, because the Docker ecosystem is so Unix-centric.  With WSL, the performance of Docker Linux is sufficient - with the caveat that volume mounts are extreme slow when using Fat32 file systems.
