### ISSUE TITLE
commandbox, runwar and server run as root user

### ISSUE THREAD

**Issue by goochjj** [Ortus-Solutions/docker-commandbox#24]
Dockerfile should create a specific user/service account to run under, instead of using /root as the HOME, and root as the user account

**Comment by jclausen** [comment]
Thanks for your submission @goochjj !

Having worked with other containers which run under a different user account ( e.g. PHP ), this creates more problems than it solves - especially in the building of production containers and volume mounting.  Since the containers operate in isolation, unless privileged access is granted ( not recommended ), running the service root is not the concern it would be with a typical VM or dedicated machine.

I'm going to close this one out.

**Comment by goochjj** [comment]
I understand that root + capabilities limitations + namespace-ing is different than "full access root", but what that means is your server is running as a credential that has full read AND WRITE access to the filesystem of your container.  While your host may be protected from the container, the container itself is at risk.

If the Lucee process can be compromised, then the process can write anywhere. It can rm -rf /app/* and delete all your source code.  It could install malware and start the process in the background.  It could just modify your source code in any number of subtle or not-so-subtle ways.

Step 2 of the Adobe lockdown guide is picking a service account for coldfusion to run as.  (Step 1 is verify prereqs)  It's not a step that should be skipped.

In my opinion - the problems you're solving (i.e. volume mounts) might be useful for development, but have no business being used in production.  (I say this as the general rule.  I AM using them in production, but I've made appropriate accommodations for filesystem permissions)  The container build process for prod containers NOT using volume mounts should be unaffected - your Dockerfile can chown things.   You need only make sure things are chown'd properly before warmup, and the warmup uses the correct startup credential to verify proper operation of the container. (In fact, I have a testbox suite I run in the container to verify the build)

I think it's the responsibility of a docker container maintainer to promote good security practices whenever possible, especially for those who aren't as versed in the downsides as you and I are.  Most people are used to running in a Windows environment.  They don't know the security model of Linux.  They're going to run it and forget it.  It may mean providing different containers for Dev vs Prod.  Or you may decide that you're going to handle the dev case, not the prod case.  And I guess that's fine.   I'm just offering my opinion.

**Comment by jclausen** [comment]
That's a good pushback @goochjj .  I believe it also illustrates the paradigm shift of containerization - moving to thinking of the "server" as temporal, rather than fixed hardware. The lockdown guide is designed for dedicated or virtualized hardware.  It's really not as much of a lockdown as it is a hindrance to the single-user, containerized environment.

With Docker, if there is a breach, in 99% of cases, I can simply destroy the container and restart with an uncompromised version of the image, without affecting any system resources on the host ( unless mounts are in place and are compromised ) and then build a better, more secure, version of the image to fix the vulnerability.

The node and PHP/Apache and Node containers are set up with a different user ( due to Node and Apache's disallowance of a root user to run the server - which is part of their binary ) and, in my experience, this creates all sorts of barriers to entry and headaches when building - especially if the building of static assets or installation of dependencies is accomplished in phases using containers in the build phase - you have to chown to one user and then back to the other over and over again.   This is why you see most of the app, database, and caching server containers - Scala, Ruby, Elasticsearch, Redis, Memcached, MSSQL, MongoDB, MySQL MariaDB, etc. - building and running as root.  Even the official Tomcat container runs as root.

If we add all sorts of `chown`-ing requirements in building and mounting, my concern is that we end up creating all sorts of barriers to entry which make it harder to adopt, without providing much in the way of a tangible security benefit ( e.g. - Lucee is still going to be able to wipe the contents of the `/app` directory if there is a vulnerability, because it needs to have RWE permissions )  If you want your container to run as a non-root user, all of this can also be accomplished from the build Dockerfile ( which I can add instructions to the README on this, as well ):

```
FROM ortussolutions/commandbox
# Create our Lucee User
RUN groupadd --gid 1000 lucee \
  && useradd --uid 1000 --gid lucee --shell /bin/bash --create-home lucee
# Change the home directory of our server
ENV SERVER_HOME_DIRECTORY /home/lucee/serverHome
# Change ownership of the /app directory
RUN chown -r lucee /home/lucee /app
# Run all subsequent commands as lucee user
USER lucee
```

I am going to re-open this so that I can add instructions on how to change the user account of the image.  That's a solid piece of information to have.

**Comment by lmajano** [comment]
I think that we should offer an optional user flag @jclausen so that we can setup the server to run as that user.  At Dockercon they spent a lot of time talking about the risk of running processes as `root` just like any other process.  The best practice of encapsulation still applies as per their engineers.

With that said, it would suffice for us to at least offer the option.

**Comment by goochjj** [comment]
I disagree with "( e.g. - Lucee is still going to be able to wipe the contents of the /app directory if there is a vulnerability, because it needs to have RWE permissions )"

In our environment Coldfusion does NOT have write access to our source.

Really what you need is

nginx runs as www-data, group www-data
Lucee runs as tomcat, group tomcat, adtl group www-data
Source code is owned by src, group www-data

All source gets u+rwX,g+rX,o-rwx

nginx can read source (assets really, and cfm existence)
Lucee can read source
Lucee can write to itself - i.e. the Lucee folders, WEB-INF folders, etc should all be owned by the lucee user, not the src user.  After all, it needs to expand bundles and write to its config file, modify the cacerts, etc.
Lucee cannot write to source


And sure, if Lucee runs as root and trashes /etc or /root or whatever, you can just restart the container... But the lucee dev list just had a ransomware post this morning - and if /app is writable by lucee (which I'm suggesting it NOT be) that could be bad. (I mean it was windows, but still.  And you should be using Git. And people never leave things uncommitted..... or unpushed)

I also agree that at the very least it should be specified in the README which already does a good job of showing how to modify the container :)

**Comment by jclausen** [comment]
@lmajano : You can provide a user to run the container in the `docker run` command and bypass the `USER` declaration in the `Dockerfile` example, above.  You still need to create that user and set the server home, though, plus provide execute permissions on the `run.sh` file.  There's a lot of hoops to be jumped through to handle that through `ENV` and a custom `Dockerfile` would be much easier and more reliable, IMHO.  I'll see if there's any feasible way to do that, though. One thing I can definitely do to make it more multi-user friendly is move the runtime scripts in to `/usr/local/bin` and out of `/root/build

@goochjj :  Again, your example provides a conventional, multi-user, server model.   In this case, in production, the CFML server ( the container ) would a reverse proxy target for the load balancer or web server and the multi-user, conventional web-server hardening model is not as applicable, due to the constraints on the container filesystem and mount points provided by the Docker platform.

Please believe me me when I say that I'm truly not trying to be argumentative and am always open to improvement and enhancements to the Docker images.  I've just been down this path with other containers and feel like making a non-root user the default container runtime account creates more problems than it solves for the variety of ways in which the container may be used.  Containers can also be used to run one-one off tasks during the build process ( e.g. `docker run --rm -v $(pwd):/app ortussolutions/commandbox bash -c 'box install` )  and may touch the file system in a variety of ways during the build.  With non-root users running those one-off tasks you're going to be dealing with permission setters at every phase of the build.

Unless you have an application that's not dealing in any user-uploaded assets ( in which case there's no place in the code which would touch the file system, anyway ), the CFML server is going to have to have some write permissions in the chain of files in the directory.  There's no way of knowing, within the conventions of each individual app being run, which directories require that access and which don't, which means that it's still going to be up to the individual developer to extend and `chown` all of those - which creates complexity and additional points of failure.  Docker mounts also protec the host in that there is no ability for upward recursion as the `aufs` driver mounts that single directory and its contents in isolation ( you can't `../` on any mounted path to gain access to the host file system ).  Mounts are only as vulnerable to the access of the container as you make them.  And the vulnerability of the Docker host is a separate concern from the container's.

That said, I can see a legitimate case for disallowing that access, in certain circumstances.   I think the `Dockerfile` extension provides that, while keeping the barrier of entry low for the majority of use cases - which is a main concern of this image.

@lmajano  and I did discuss this afternoon, the strategy of specifying read-only areas of the container filesystem, which Docker allows us to do.  We plan to implement that in a future iteration of the container, though we have to be careful on that to allow downstream extension of it, as well.

I'm also going to add a security section which contains additional hardening information ( like changing the runtime user account ) and note both the caveats and benefits discussed in this issue thread.  

I really appreciate you opening this issue. It lights the fire under our tails to make this image even better! I will keep you updated with documentation and enhancements we make which are related.

**Comment by lmajano** [comment]
🔥

**Comment by jclausen** [comment]
@goochjj :  The current `*-snapshot` tags on Docker Hub ( https://hub.docker.com/r/ortussolutions/commandbox/tags ) now have an option to pass a `USER` environment variable ( e.g. `docker run ortussolutions/commandbox:lucee5-snapshot` ) which will run the servers under the user account provided. 

If you could try the images out which might be applicable, and let me know if there are any issues, I will bump a new release in the next couple of days.
