### ISSUE TITLE
Support for HTTP2

### ISSUE THREAD

**Issue by samihoda** [Ortus-Solutions/docker-commandbox#45]
If we enable HTTP2, by adding this to our server.json file, 
"runwar":{
        "args":"--http2-enable=true"
    }

then Undertow changes the default HTTPS port to 1444 (instead of 8443, see https://github.com/cfmlprojects/runwar/blob/a233cd3f343b27250e8d9fc2724f0cccbb2dc784/src/main/java/runwar/Server.java#L544). I'm hoping there is a way to override that, but in the mean time, all docker-commandbox code seems to assume 8443 will be the SSL port. 

To fix, it would seem, we would either need to make port 8443 a variable, and if HTTP2 is enable, choose 1444, or find a way to force port 8443 in runwar for undertow.

**Comment by samihoda** [comment]
Looks like 1444 (1443+1) maybe a mixture of the runwar code which add one, and 1443, coming from here https://github.com/Ortus-Solutions/commandbox/blob/316af6a5186b43570496c4d66159dfb6532d6fdf/src/cfml/system/config/server.schema.json#L289

**Comment by jclausen** [comment]
@samihoda : are you looking to add support for HTTP2?  From other posts on slack it looked like you wanted to make sure it was disabled.

If you want to use a different HTTPS port, you can simply add an HTTPS_PORT environment variable with the alternative.

If your goal is to expose HTTP2, then you can do this with a custom Dockerfile build or just port map the host to 1444

**Comment by samihoda** [comment]
@jclausen I wanted to make HTTP2 a first class player. Being forced to use port 1444 by Undertow however is what is problematic, as all the examples reference 8443.

**Comment by jclausen** [comment]
@bdw429s : any update on getting the extra port issue resolved in Runwar with HTTP2 ?

**Comment by bdw429s** [comment]
No.  My message to the Undertow list to ask for clarification on how HTTP2 is supposed to work was never replied to.

**Comment by samihoda** [comment]
Is there anything public we can comment on or +1 to bring attention?

**Comment by jclausen** [comment]
@samihoda : This really isn't an issue for docker as both 8080 and 8443 are serving http2, once the setting is enabled.  You can see this using the HTTP2/SPDY plugin for Chrome.  Since this port isn't exposed from the container, it's really only a problem when starting multiple CommandBox servers with HTTP2 enabled on a single host.

I'm going to close this issue out and let @bdw429s deal with it through CommandBox JIRA stories.

**Comment by bdw429s** [comment]
@samihoda I posted to the JBoss `undertow-dev` mailing list in Feb with a subject of "Support for HTTP2" and followed up in March.  Their mailing list is using some horrible, old GNU Mailman software and is located here

https://lists.jboss.org/archives/list/undertow-dev@lists.jboss.org/

I'm actually rather confused because I can't even find my thread on their site now and I get an error when trying to manage my subscription preferences.  Sigh.  I reached out tot he Redhat employees to manage Undertow to ask if their list is even working.  It was always low traffic, but doesn't seem to have had any posts in a while now.

**Comment by samihoda** [comment]
@jclausen @bdw429s Is there a Jira ticket for CommandBox that I can note my concerns about being locked to 1443/1444 to, if this shouldnt be related to Docker? Just want to make sure the original issue doesn't fall through the cracks.

**Comment by cubortea** [comment]
@jclausen is it correct now the docker-commandbox 5.2.1 image using OpenJDK 11 now?

**Comment by jclausen** [comment]
@cubortea - `ortussolutions/commandbox:commandbox-5.2.1` would now be based on JDK11.   If you want to pin to 5.2.1 on JDK8, you would use the tag `ortussolutions/commandbox:amd64-jdk8-3.3.0`  to lock in the architecture, JDK, and the image version

@samihoda - Looking at JIRA it looks like @bdw429s never created a ticket for it, so I added this one, which should cover the root issue: https://ortussolutions.atlassian.net/browse/COMMANDBOX-1275
