### ISSUE TITLE
Unable to reach CF admin on image tag 3.2.0

### ISSUE THREAD

**Issue by adamrr724** [Ortus-Solutions/docker-commandbox#54]
We are test running both CF18 & CF21 on the latest versions of the commandbox docker image (3.2.0) and are running into an issue where our applications are working fine, but the admin page is coming up as "Not Found". 

If we use the image tag 3.1.0 -- the admin (at /CFIDE/administrator/index.cfm) works as expected.

Happens when targeting multiple commandbox versions & CF engine versions, on Mac & Windows. 
  
Let me know what other information you need to investigate further.

**Comment by jclausen** [comment]
@adamrr724 :  After verifying with Brad, this is actually a feature in the latest version of CommandBox and relates to the "Secure by Default" updates that the latest version of CommandBox has. I noticed this, myself, just yesterday.

Because the container server binds to 0.0.0.0, the "production" profile is turned on ( https://commandbox.ortusbooks.com/embedded-server/configuring-your-server/server-profiles ), which disallows access to the CF Admin from anything other than 127.0.0.1 ( when you hit the container on 127.0.0.1 from the docker host, it's not actually localhost inside of the container ).  

I'm going to add some documentation on this today, but the workaround is to set this key in your `server.json` : `web.blockCFAdmin=false`.  That will allow access to your container's admin again.

**Comment by adamrr724** [comment]
@jclausen  Thanks for the explanation, that makes sense. Added that key in my server.json and everything is working as expected!
