### ISSUE TITLE
.cfconfig.json not being applied with latest docker images

### ISSUE THREAD

**Issue by ravensorb** [Ortus-Solutions/docker-commandbox#65]
I've been working on upgrading to the latest docker image (last time I rebuild the image I think I was using commandbox 3.x with adobe 2016) and it looks like a lot has changed since then.  Right now I have a clean .cfconfig.json file that has 1 custom datasource and a custom adminPassword.  

```
{
    "requestTimeoutEnabled":true,
    "whitespaceManagement":"white-space-pref",
    "requestTimeout":"0,0,5,0",
    "cacheDefaultObject":"coldbox",
    "caches":{
        "coldbox":{
            "storage":"true",
            "type":"RAM",
            "custom":{
                "timeToIdleSeconds":"1800",
                "timeToLiveSeconds":"3600"
            },
            "class":"lucee.runtime.cache.ram.RamCache",
            "readOnly":"false"
        }
    },
	"datasources" : {
		 "dsDB":{
			 "dbdriver":"mssql",
			 "host":"192.168.1.20",
			 "port":"1433",
			 "database":"db",
			 "password":"dbpass",
			 "username":"dbuser"
		 }
	},
	"adminPassword": "pass@w0rd1",
}
```
I have an .env file that looks like this
```
BOX_SERVER_APP_SERVERHOMEDIRECTORY=/config/serverHome 
BOX_SERVER_CFCONFIGFILE=.cfconfig.custom.json
BOX_SERVER_PROFILE=development 
BOX_SERVER_WEB_REWRITES_ENABLE=true 
```
I have this in a folder that contains
* server.json
* .cfconfig.custom.json
* index.cfm

when I run the docker image, everything starts and I can load up the index.cfm and the CFIDE Administration pages.  However when I log in to the CFIDE Admin, I nee to use the default admin password (not the one specified in the cfconfig file and when I look at the data sources my custom data source isn't setup.

Is this a bug? Or am I doing something wrong?

**Comment by jclausen** [comment]
@ravensorb Because your `cfconfig` file has a custom name, it is not being picked up automatically on server start.  CommandBox is looking for a file named `.cfconfig.json`.

In order to use your `.cfconfig.custom.json` you are going to need to specify that as the `cfconfigfile` entry in your `server.json` file.

**Comment by jclausen** [comment]
Ah! Sorry. I see that you have that declared in the environment. I believe and @bdw429s can correct me if I'm wrong, that key cannot be used as an environment variable, because it is needed too early in the server startup.   At least I remember something to that effect.  My suggestion would just be to mount that file in as `.cfconfig.json` instead of trying to customize it.

**Comment by ravensorb** [comment]
I thought the point of the ENV variable BOX_SERVER_CFCONFIGFILE was to support custom file names?

**Comment by ravensorb** [comment]
Update -- that seems to have worked.  So I take it either this is a bug or that ENV variable is no longer usable?

Note: This is an .env variable for the docker container so it should be available at the very beginning of the lifecycle correct?

**Comment by jclausen** [comment]
@ravensorb : Actually, can you try something for me? I'm not sure I'm right on that environment variable, but I believe the issue may be with the `.` at the beginning of the filename.

Try it as:

```
BOX_SERVER_CFCONFIGFILE=./.cfconfig.custom.json
```
or
```
BOX_SERVER_CFCONFIGFILE=/app/.cfconfig.custom.json
```

I have had issues with that key being a relative path and starting with a dot before, when using it in `.server.json`

**Comment by bdw429s** [comment]
@ravensorb Firstly, I don't think our docker images come with the `commandbox-dotenv` module out of the box, so unless you're specifically installing that as part of your build (which isn't clear from your description), your `.env` is a nice paper weight.   You can confirm this quickly by SSHing into your container and running this
```bash
env show
```
from the folder with the `.env` file to see if those env vars show up.

Secondly, I think there was a bug a while back where `box_server_cfconfigfile` env vars weren't getting picked up due to an oversight in how CFConfig read the `server.json` but didn't load the env overrides.  Depending on what version of CFConfig is bundled with your image,  you may be on an old version without the bug fix.  Can you update CFConfig to the latest in your build?
```bash
RUN box install commandbox-cfonfig --force
```
And finally, there is a fair amount of debugging information built into the verbose server start logs that tells you what CFConfig is up to.  Please provide the full console logs from your container when it boots up (removing any sensitive data).

I just ran a test in pure CommandBox and it seems to work just fine.
```bash
CommandBox> echo {} > foo.json
CommandBox> set box_server_cfconfigfile=foo.json
CommandBox> start --verbose --dryRun
```
and the console output includes this:
```
|------------------------------
   | √ | Overriding server.json values from env vars
   |   |----------------------------------------------------------
   |   | Overridding [cfconfigfile] with box environment variable [box_server_cfconfigfile]
   |   |----------------------------------------------------------
```
and a little farther down
```

```

**Comment by bdw429s** [comment]
> I have had issues with that key being a relative path and starting with a dot before, when using it in server.json

@jclausen Please provide a repro case if you have one.  I've never heard of this being an issue and I also ran my test above with a file called `.foo.json` and it worked fine as well.

**Comment by jclausen** [comment]
@bdw429s All of our images do come with `commandbox-dotenv` out of the box.

**Comment by jclausen** [comment]
@bdw429s I will take a look and try to get you a repro case on the pathing.  We ran in to the issue recently with a client when using the the services manager and changing it to an absolute path seemed to resolve the issue.

**Comment by bdw429s** [comment]
@ravensorb BTW, I should probably mention CFConfig also supports a top level env var called `CFConfigFile` (which predates the ability to override `server.json` properties generically).  
https://cfconfig.ortusbooks.com/using-the-cli/commandbox-server-interceptors/server-start#environment-variable
That will probably work for you, but I hadn't mentioned it just yet since I did want to get to the bottom of your current issue.

**Comment by ravensorb** [comment]
Thanks -- still a bit confused though.  Looking at this page https://hub.docker.com/r/ortussolutions/commandbox/

Under the section for environment variables, it calls out the variable BOX_SERVER_CFCONFIGFILE which is what I was trying to use.

docker-compose file looks like
```
version: '2.1'

services:

  test:
    image: ortussolutions/commandbox
    environment:
      BOX_SERVER_CFCONFIGFILE : .cfconfig.custom.json
    volumes: 
      - ./app:/app
    ports:
      - "8080:8080"
```

Note: I did not try this yet
```BOX_SERVER_CFCONFIGFILE: /app/.cfconfig.custom.json```

**Comment by jclausen** [comment]
Your confusion is warranted.  @bdw429s is looking in to this too, as I can replicate the issue on my Mac, but his Windows machine loads it correctly using the environment variable.

**Comment by ravensorb** [comment]
if it helps -- I am trying this on a linux box as well (same issue)

**Comment by bdw429s** [comment]
The other factor is I have the current bleeding edge version of CommandBox on my PC where everything seems to be hunky-dory so it's also possible there was a bug in the stable version of CommandBox that has already been fixed.  Which is why I mentioned the `cfconfigfile` env var above.  I've had other people with a similar complaint to yours and we never got to the bottom of it (mostly because they stopped replying in Slack) but they DID report that the `cfconfigfile` env var worked for them.  So if you just to get on with your day, you can switch over to that one.

**Comment by ravensorb** [comment]
Happy to help test for a fix, or when you push your next update -- I can test with that.

**Comment by bdw429s** [comment]
@ravensorb Did you see the workaround I gave you a few messages back?  Did you try it?  Did it work?

**Comment by ravensorb** [comment]
@bdw429s I did and it did -- if I use the standard name it seems to pick it up and create the data sources correctly.

**Comment by jclausen** [comment]
Closing, as this seems to be specfic to `commandbox-cfconfig` or CommandBox itself on linux and it is not related to the docker build, iteself
