### ISSUE TITLE
Error on start latest container

### ISSUE THREAD

**Issue by Willeye-uk** [Ortus-Solutions/docker-commandbox#82]
When i pull latest container and start it gives error

ERROR (6.0.0+00787)

java.lang.StackOverflowError

/usr/local/lib/CommandBox/cfml/system/modules/globber/models/Globber.cfc: line 330
328:
329:    private function processPattern( string pattern, baseDir, skipExcludes=false ) {
330:            local.thisPattern = pathPatternMatcher.normalizeSlashes( arguments.pattern );
331:            var exactPattern = thisPattern.startsWith('/');
332:            var fileFilter = '';
called from /usr/local/lib/CommandBox/cfml/system/modules/globber/models/Globber.cfc: line 434
called from /usr/local/lib/CommandBox/cfml/system/modules/globber/models/Globber.cfc: line 457
called from /usr/local/lib/CommandBox/cfml/system/modules/globber/models/Globber.cfc: line 434

**Comment by Willeye-uk** [comment]
Seems to caused by undertow rules file.

**Comment by Willeye-uk** [comment]
If server.json contains 

        "rulesFile": "../.site.rules"

and if file is not found. causes error above

**Comment by bdw429s** [comment]
This is the wrong repo for this. The issue is in CommandBox.  I've seen a couple other people report this, but no one has been able to provide a working reproducible case and I haven't been able to reproduce it on my own.

Possibly-related ticket:
https://ortussolutions.atlassian.net/browse/COMMANDBOX-1532
